// Package store implements the Postgres-backed persistence layer.
// It is the only package that contains SQL. Its responsibility is to isolate
// database implementation details and translate database-specific errors into
// standard domain errors, ensuring the rest of the application remains
// database-agnostic.
package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/Ashfak-Hossain/shortn/internal/shortener"
)

// Postgres is the concrete implementation of the shortener.LinkStore interface.
type Postgres struct {
	pool *pgxpool.Pool
}

// Compile-Time Assertion:
// This blank variable forces the compiler to verify that the *Postgres struct
// strictly implements all methods of the shortener.LinkStore interface.
// If the interface changes and we forget to update this file, the build fails immediately.
var _ shortener.LinkStore = (*Postgres)(nil)

// New initializes and returns a Postgres store backed by the provided connection pool.
func New(pool *pgxpool.Pool) *Postgres {
	return &Postgres{pool: pool}
}

// Create inserts a new link into the database.
// It mutates the provided link pointer by populating its ID and CreatedAt fields
// with the values generated by the database.
func (p *Postgres) Create(ctx context.Context, link *shortener.Link) error {
	const query = `INSERT INTO links (code, long_url) VALUES ($1, $2) RETURNING id, created_at`

	// We use QueryRow instead of Exec to execute the query and scan the RETURNING
	// values in a single database round-trip.
	err := p.pool.QueryRow(ctx, query, link.Code, link.LongURL).
		Scan(&link.ID, &link.CreatedAt) // If the code already exists, return ErrCodeExists instead of a pgx error.

	if err != nil {
		var pgErr *pgconn.PgError
		// We check for the specific Postgres unique constraint violation code (23505).
		// If the short code already exists, we translate this into our domain's ErrCodeExists
		// so the HTTP layer doesn't need to know about pgx errors.
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return shortener.ErrCodeExists
		}
		return err
	}
	return nil
}

// GetByCode retrieves a link by its unique short code.
// It returns shortener.ErrNotFound if no matching record exists in the database.
func (p *Postgres) GetByCode(ctx context.Context, code string) (*shortener.Link, error) {
	const query = `SELECT id, code, long_url, created_at, expires_at, click_count FROM links WHERE code = $1`

	var link shortener.Link

	// We map the raw database row directly into our domain struct.
	err := p.pool.QueryRow(ctx, query, code).Scan(
		&link.ID,
		&link.Code,
		&link.LongURL,
		&link.CreatedAt,
		&link.ExpiresAt,
		&link.ClickCount,
	)
	if err != nil {
		// We translate the pgx-specific "no rows" error into a standard domain error.
		// This prevents database implementation details from leaking to the caller.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, shortener.ErrNotFound
		}
		return nil, err
	}
	return &link, nil
}
