apiVersion: v1
kind: Secret
metadata:
  name: shortn-api-secret
  labels:
    app: shortn-api
type: Opaque
stringData:
  DATABASE_URL: "postgres://dev:dev@shortn-postgres:5432/shortn?sslmode=disable"
  REDIS_URL: "redis://shortn-redis:6379/0"
