{{- if .Values.sealedSecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortn-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCGNZsyajtdHWXHzn+SgPJtORIN2MAIBtgh6+vGu2vIIcC73JMaHANzaRfI9KLKgDzK1QQLvGqe58/QYcCkmdJbvJvMcx+Rwyyjdx7WwPh7MJXBvrYGcSjSp7Oz6xt5rHSC+odFaLzNSDMZskMzgabwSdMFYM/2/9haULbuAdZA9IyEGYyajNTFVVH5cUIDU04vvMTI1NL09mq+PiMHFq72Oq//Z9oDUIww7P8VKCZMNV+Ojdl5hmKJhUxzabaP9cZcKU+LlyQWolUiIfNawmf1qWr+FJsO4DD7ozgZqCBOZNkdBSg62IWqVQw73k9MTVkt3fsBPnx5rgKPlyuO1xy4X+Q3OLT5YidytJHr1uAC91KfpHLS3wTf86qbxm0o5QAETzaT1NehqmR+COcVFZ3T3QhGwZBsMmrkBjtRCWSraXp72576AidC2zlb5TOVni1sdFQ8TF2zj5wBuE6aim5J4bJV9/ThTc5u1ZfxL6AHo5k6oKxI84JR/NDDOOzIcTYyDZcp4LbaNz7nqOHk8kuHSeVXokUbp/zh/4KBZ087pepQAE6G4mgpvSDByOn5ZSifUmYNp6vSXDjF++exOpKKMoWw/WEqVpIR/Duk32vE+0FWZQpeAQhvPnTobeuIfc/QMOr+uOyM/+PWSviOi9YhWoMRfhkWFSMRg/oHkhzhfd1SPoqUx7dGoO6ABzYN9KhJJpRW5IWMAWpPqNhofcjazFdwvJFNYwNpGvuDDs2jg8449p/T2cVMtAMfQBcRBWk8G+iVzWFCjY98hDrbcA==
    REDIS_URL: AgCEJNtoPw501xFZfdsemy06H6OIXDDvEouRIDgueF/4Q9arZL8V7+E5yKc/w1CjOHcPBhCquTBvDKtZMA20b+ifeecS4lnckpU02w1kGf5K2Aq+K0fKWQEqB+j8BTk/nTxXr75nni87M+IIItCOcNIx8L7pS9F/jWfTuzXe8taEDc2EFDt9Qdv9+53S7BacgVFSpGK/X2bQRtCjEvSPqgZ78udGj6SWO7CaWb60ucY5A6RZt19Lt7P+4nv9dcBZVHiaqlaTqAi+n56scTEN99yZFpWizsSpZkTPI1kmy1n3HwyTmx5Zo9ss5BmetJvgb1sWss+6QKeg80oOodIMAwkdJ2+eNkh58Oh6/PcvP3CMzsI27OKkqZ3xxI2dD0UJLg9KvaK6N0WRQA3NGAzO7ezZVNi8ob4dOMYL2IWyDERC9ojO/VQcH206o/A4FOWa0LTObYm/N5fHaC7+HwYgBWMrThcldTnuUn9UUaMhiE1rN3B1XdrRdWHgHNkGfpRU7MgXeWbq8Cat41EMKzmvvTIpgT8tK3yt5StkW/9wxRRtCf8lUIyWQ5XP5UdgmQgyARQ4Q++FnigRDGNvNwa/8/m3snsFctmLkPqSQk/6yno5F6+g57F5VjOxO6DlHOQVRumhupsYx7Bz+qB0Q5Eu9XTk6ly1vNeIVwus3YeUnnnTCpgGc+j+R03vAcXMn7Dg5v82/iL8Hz1w+1OMEnBJxrlLrAMnuaDnyKAtnVs=
  template:
    metadata:
      name: shortn-api-secret
      namespace: default
{{- end }}
