---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortn-api-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgBI789KJapY15LF8fxwP3R84VOWEKlXbzQ/zepZB3EB4Yqmi4AZ7uQtyG2mF4ct4K1RaQVE3yoh4J2re5Zi57NzBBRYHK2cdHynoFJ5p+1nwQw8As0Fs0r4Q48bvBayl3phjQD30ziHbgYn2l0XnrRZhCcONaP791Yq8iQRwgzCgxFmR63XTK3HNg2L6sfBl7lXFQ+RmBpcIEjyF6645djBtfKHXmlFhQ72WuswdiObNCCNnkbjrQktnGt15WjWGKyKEP9TSNaCu/Zu1dlUOVsx4P/VIdC1nVIRaj5G0YEHaGOOREpT2/Jr95Eberoj1TVFpUutRzmaSipk3q1S8A9zs9k2JHagWfwvl34HefssekOBggwMqPYQf56TfCxpgUNNiwmymPq3l2LlXy5G51Su9qXMPVjwZY3n+nDIAqzMgd7tfv07DpxkMt0ETfe374F9aXS9uyTVdh+6Bh2cih4eR7Kyk8vZDY2FLBEbqLO84mDv+dKd68oBeB5poHnG9AAVwnwDyvBSPY2sveeObCa8TRjDSFgcBSc/makQPvB0KT+AW0Gm+iQhFu0NuHjm7pgAods3Sk/8BXp3cRd+KGrlVuC7cMtwt4KHOI3xuy/eRqj3h0xpDwsLyQfqkiMIPf7R/5hQCHezgYJ/oov170tjD+GJnhr1xJXNRvAAg1RetKWJnZH4rYHVdIpQg7XMUEYQqha3CdARrXFtl6qfPlPRYosLjf6EeavgmxjAmb/wCvfdsXsBqNrqU9BzkgZmAqFRdjcnw+21l9QtCzPLnw==
    REDIS_URL: AgAm0jV4HvojFDaCuNbSgtbFHi43zQsut3GOI4VSazROFDFigGV0DEbgP5CtcdmcwrNYfmAkuzJqp7+ZBiR95rEC/7A8OSk9rPOnYa9aG/sWHkbqx69kHZwmxISXfzzCJbu7Po71mrcjgbLuGDwyviIw4lWKxpNK3BH0bip3eiERnLo87VJqTt//Aa1cGl4+mimIkfASSC9LgcZKybeZtk2b3r+gmwExa7kRLLD73Abw6zZrY61AjynyTNHmgqSMU4K88Yl/Gxt3/lnzcQhXU8UeMxc+HaCzJYG8lTsVY6GNaSGJdEI5KdQl8YYBDMwagcrqdupusJKWT54/Oafflx3eLjL5Iw2OSIESEDC2V+X/zQ+58XQesMuB4aeNQxhYB8emOircOY7KAdITeDBS8Dv976Gq7WGYkpRrUlXvkoUj8/UrBvcaGlHT1c6kikk6dh039l15uWlhXBaHV40PSSFfswML+Mp2fFts2vqE17fz2GkdgArWVz3TS+yApH4pqLlTXKbLndzgw3IJ6EVDR7SG9cAx3SXQeBYprTBiAwqTjG/0YiUI5305MeAto27X0XgIhz6X8u5NqANlhCaEad8+8FhCxuvvQPRrGh2qu7dabtf4Q5884S3tj2jNzpR0j+ocODF40N7YxXhBq+Nr4god2X+/9DnIio+aBT5moeNdQMspEGY5cmaQ7UXDyQ0iD174YPHti3MbGG481uA5yvsmKSht7DMltU4eCLc=
  template:
    metadata:
      name: shortn-api-secret
      namespace: default
